### ISSUE TITLE
June 2024 roadmap

### ISSUE THREAD

**Issue by davelab6** [Lorp/fencer#30]
- [ ] Multiple views #16 #17
- [ ] Polyfill for Windows 
- [ ] New UI for source/destination mappings
- [ ] Renderings redesign #17 #23
- [ ] Customise colours and sizes
- [ ] Represent when at default
- [ ] Represent epsilon [[FontTools issue](https://github.com/fonttools/fonttools/issues/3568)]
- [ ] Represent an entire corner fence as one UI element
- [ ] avar1 layer #14
- [ ] Interpret existing avar1 and avar2 values #10
- [ ] Filter mappings by dimensionality (consult with Berlow team)

Can any be checked off already?

**Comment by Lorp** [comment]
All cool stuff. I’ll conduct a kind of survey of Fencer users and other parties interested in avar2, and work out priorities.
